json.extract! @user,
              :email,
              :username,
              :password,
              :skill_type,
              :gender,
              :city,
              :about_me,
              :experience,
              :compensation,
              :avatar_img
